name: megnet-tests
on: [push]
jobs:
  Pytest:
    name: InstallAndTest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
        mne-version: ["1.5"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: false
          channels: conda-forge  
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
      - name: Install MNE
        shell: bash -el {0}
        run: $CONDA/bin/conda install --name test --strict-channel-priority --override-channels --channel=conda-forge 'python=${{ matrix.python-version }}' pytest 'mne=${{ matrix.mne-version }}'  
      - name: Install Git
        run: sudo apt install git -y
      - name: Pip Install Megnet
        shell: bash -el {0}
        run: $CONDA/envs/test/bin/pip install git+https://github.com/nih-megcore/MegNet.git
          #- name: Download test data
          #shell: bash -el {0}
          #run: make get_data
      - name: Pytest
        shell: bash -el {0}
        run: $CONDA/envs/test/bin/pytest
  
